spring.application.name=cinema-management

spring.datasource.url=jdbc:mysql://localhost:3306/cinema?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=111111

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Bật debug cho Spring Security
# logging.level.org.springframework.security=DEBUG

# Nếu muốn log chi tiết hơn (nhiều hơn cả DEBUG, chỉ nên bật khi test)
logging.level.org.springframework.security=TRACE

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
spring.jackson.serialization.fail-on-empty-beans=false

# Cho phép Vue gọi API
spring.web.cors.allowed-origins=http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

#VNPAY
vnp_TmnCode=7VOTMC7T
vnp_HashSecret=2DB30MPL59CBE6RGIO5Y4CLSMEC4N3AU
vnp_Url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp_ReturnUrl=http://localhost:5173/payment-result

app.seed.enabled=false
